In [22]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [23]:
path = "../dataset/diabetes_binary_5050split_health_indicators_BRFSS2023.csv"

df = pd.read_csv(path)

# Target
y = df.iloc[:, 0].values

# Features (same as dataset[:, 1:-2])
X = df.iloc[:, 1:].values

In [24]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [25]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

print("Original dim:", X.shape[1])
print("PCA dim:", X_pca.shape[1])
print("Explained variance:", pca.explained_variance_ratio_.sum())

Original dim: 22
PCA dim: 20
Explained variance: 0.9594954136087605

In [26]:
display(pd.DataFrame(X_pca))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-2.228419,-0.721119,0.287231,-0.704049,-0.851273,-0.552051,0.218101,0.092970,0.149644,0.267307,0.546861,0.073411,0.161255,-0.488916,0.223387,-0.336616,-0.076332,-0.343036,-0.767926,1.398255
1,0.308655,-0.025929,1.945765,-1.206372,0.618934,1.297513,-1.289085,0.317544,-0.565072,-1.171760,0.305598,0.137716,-0.124798,0.765235,-0.044943,-1.229132,0.834732,0.450819,-0.501259,0.392796
2,0.333544,-2.264662,-0.676865,-2.965711,-1.437477,0.168955,0.764584,0.921479,-0.196882,0.163485,1.662290,0.702777,0.378414,-0.952759,0.115423,-1.292698,0.892848,-0.478933,-0.666447,-0.074236
3,-0.774347,-2.398105,1.053244,-0.889982,-0.467229,-0.141574,1.102996,0.488177,0.055427,0.249546,0.789820,0.189855,0.528600,-0.244654,0.061892,-1.843855,0.983076,0.598212,-0.496823,0.734482
4,0.467442,0.435641,-1.990970,-1.412570,-0.962953,0.706497,0.737213,0.946278,-0.216379,0.326582,0.591981,0.190077,-0.273926,0.578268,-0.241780,0.430497,0.956736,1.278975,0.487900,-0.863424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71809,-1.217324,0.395488,-0.502855,-0.814593,-0.593838,-0.692154,0.929095,0.852734,-0.080073,0.030459,0.185739,-0.802877,-1.095529,0.183161,-0.555578,-0.406244,1.202594,0.273881,0.574836,-0.414424
71810,-0.839856,0.734372,0.621860,-0.286911,1.102702,0.049243,0.749542,1.111725,-0.346846,-0.411102,0.194437,-1.326899,-0.602696,0.276876,-0.410955,-0.056776,0.942218,1.181694,-0.596789,-0.095707
71811,-2.435610,-0.258585,0.346002,0.267391,0.308028,-0.532937,0.339391,0.904175,0.283992,0.297005,0.460046,-0.346856,-0.168348,-0.390417,-0.143088,0.095183,0.080419,-0.283678,0.369732,-0.472758
71812,0.755307,0.346455,-1.588702,-2.797912,-1.018796,0.346759,-0.623645,-1.030364,0.185856,0.154119,0.232904,1.703482,0.242281,-1.564343,-0.618185,0.081448,-0.018896,-0.164062,-0.466754,0.391777
71813,-0.393643,0.909513,0.112072,-1.256260,-0.206297,-0.290909,-0.670958,-1.455649,0.188775,-0.143803,-0.800367,0.466407,0.082022,-0.632623,-0.217559,0.362602,-0.223702,0.282947,-0.013422,-1.390490

In [30]:
feature_names = df.columns[1:]  # same slice as X

loadings = pd.DataFrame(
    pca.components_.T,
    index=feature_names,
    columns=[f"PC{i+1}" for i in range(pca.n_components_)]
)

loadings

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20
KidneyDisease,-0.099149,-0.099020,-0.059768,-0.090283,-0.070302,0.358029,0.128709,0.028307,0.759499,-0.405748,-0.164008,-0.120703,-0.152643,-0.046265,0.075024,0.016955,-0.043586,0.024288,-0.031900,-0.006866
HighBP,0.243762,0.310341,-0.049897,-0.105238,0.288995,0.218194,-0.162525,-0.105578,-0.080167,-0.140975,-0.000382,0.023761,0.052300,-0.097081,-0.068870,0.292802,0.023230,0.563398,-0.200283,0.187686
HighChol,0.177176,0.272486,-0.016558,-0.018428,0.251382,0.211517,-0.261486,-0.355041,0.066715,-0.017260,-0.337977,0.197963,0.131437,0.064164,-0.206821,-0.414591,0.069973,-0.422127,0.086997,-0.003837
CholCheck,0.052165,0.227395,0.258566,-0.125425,-0.035357,0.180767,-0.014435,-0.226472,0.317456,0.590876,0.478091,-0.231386,-0.169258,0.034695,-0.032816,-0.085159,-0.058381,0.025532,0.050449,-0.010834
Asthma,-0.097483,0.102823,-0.305213,-0.150483,0.208070,-0.143220,0.572930,-0.177105,0.047814,0.210645,-0.174363,-0.303313,0.449850,-0.237722,0.082969,-0.038630,-0.020006,-0.012898,-0.032783,-0.003542
COPD,-0.164448,-0.007730,-0.009042,-0.259237,0.408592,-0.110451,0.367942,-0.229735,-0.017070,-0.120618,0.203657,0.462786,-0.279677,0.388382,0.151045,0.076333,-0.087402,-0.041854,0.021382,0.000603
BMI,0.182408,-0.070323,0.259903,-0.208283,0.354163,0.361763,-0.046243,0.316512,-0.136710,-0.161552,0.220284,-0.138970,0.368443,0.010652,0.274815,0.014620,-0.107468,-0.133501,0.136708,-0.118770
Smoker,0.150076,0.036641,-0.326711,0.320219,-0.241551,0.350115,0.104904,0.082387,-0.001628,0.233240,-0.073153,0.100166,0.223502,0.597644,0.218786,0.085417,-0.151156,0.028582,-0.057002,-0.018795
Stroke,0.169770,0.100190,-0.077736,0.194961,-0.041884,-0.400394,-0.059875,-0.131245,0.264070,-0.379491,0.486761,-0.066583,0.400565,0.220785,-0.256064,-0.009386,0.010466,-0.028396,-0.033409,-0.021526
HeartDiseaseorAttack,0.221633,0.209029,-0.158301,0.278315,0.081837,-0.227279,-0.086700,0.037482,0.101144,-0.049053,0.111086,0.068815,-0.186553,-0.245429,0.703775,-0.328539,0.037305,0.039585,0.000583,0.038884
PhysActivity,-0.274399,0.040553,-0.021994,0.217667,0.079605,-0.011207,-0.258102,-0.123588,0.162482,0.134924,0.025098,0.310433,0.197791,-0.330791,0.076180,0.433372,-0.508570,-0.189437,0.030158,0.055948
HvyAlcoholConsump,-0.040654,-0.071254,-0.085014,0.350162,-0.117323,0.421417,0.236593,-0.457657,-0.357126,-0.278774,0.285860,-0.129903,-0.153257,-0.244224,-0.031669,0.011860,0.021905,-0.105853,0.030077,-0.068969
AnyHealthcare,-0.007797,0.344500,0.369839,0.076046,-0.239903,0.071054,0.284659,0.117002,0.079994,0.001787,0.003745,0.360236,0.189085,-0.135314,0.087921,0.253205,0.527152,-0.178553,-0.086246,-0.017407
NoDocbcCost,0.104553,-0.383914,-0.140644,0.063052,0.252858,-0.055031,-0.254613,-0.272729,0.116491,0.160849,-0.046003,-0.185827,-0.029479,0.102718,0.184938,0.414487,0.523445,-0.164046,-0.058863,0.039897
GenHlth,0.402718,-0.065142,0.076971,0.056809,0.132250,-0.001537,0.101093,0.043015,0.017645,0.042653,-0.030681,0.034713,-0.071591,-0.089752,-0.062378,0.029907,-0.144275,-0.071498,-0.442456,-0.271492
MentHlth,0.207592,-0.323658,0.235550,0.258903,0.074403,0.015858,0.160277,-0.172786,0.139918,0.119689,-0.126997,0.279285,0.168072,-0.076652,-0.081161,-0.151145,0.041935,0.477737,0.412920,0.113377
PhysHlth,0.350545,-0.123976,0.198622,0.186441,0.060453,-0.122074,0.238860,0.013625,0.060525,0.071001,-0.152968,-0.002564,-0.183759,-0.035798,-0.160677,0.071187,-0.219971,-0.129422,-0.344350,-0.009639
DiffWalk,0.365445,0.002491,0.121041,-0.015402,-0.050159,-0.106713,0.162861,0.065950,-0.034495,-0.090046,-0.056140,-0.192986,-0.127542,0.032052,0.026109,0.246528,-0.165981,-0.315804,0.462185,0.424909
Sex,-0.041770,0.150375,-0.338572,0.332764,0.405733,0.091735,0.104585,0.468221,0.092991,0.124457,0.134141,0.033651,-0.218314,-0.098503,-0.363713,0.055640,0.170037,-0.054615,0.249381,-0.129135
AgeGroup,0.171842,0.479548,-0.145349,-0.118835,-0.148285,-0.081680,-0.001165,-0.134760,-0.044255,-0.071594,-0.208189,-0.117193,-0.188025,0.074765,-0.005340,0.263108,-0.052961,0.098653,0.193433,-0.069536
Education,-0.223676,0.155696,0.399548,0.321460,0.188677,-0.141177,-0.018590,-0.099756,-0.009201,-0.086624,-0.247364,-0.299446,-0.027771,0.216344,0.117294,0.103419,-0.062933,0.108496,0.165580,-0.513109
Income,-0.308868,0.152604,0.230218,0.316649,0.227225,0.036044,0.036567,0.067754,-0.030533,-0.031852,-0.068186,-0.221174,-0.008604,0.182273,-0.005560,-0.124588,0.011022,-0.004554,-0.293200,0.621587

In [ ]:
importance = (loadings**2).sum(axis=1)
importance = importance.sort_values(ascending=False)

importance

COPD                    0.999731
KidneyDisease           0.999701
Sex                     0.999695
CholCheck               0.999369
HvyAlcoholConsump       0.998821
Stroke                  0.998259
AnyHealthcare           0.998231
Asthma                  0.997262
PhysActivity            0.995487
HeartDiseaseorAttack    0.995064
HighChol                0.993505
Smoker                  0.991216
NoDocbcCost             0.987726
Education               0.939978
MentHlth                0.936630
Income                  0.907655
BMI                     0.894167
HighBP                  0.860783
DiffWalk                0.843112
AgeGroup                0.570713
PhysHlth                0.570110
GenHlth                 0.522784
dtype: float64

In [29]:
from sklearn.feature_selection import mutual_info_classif

mi = mutual_info_classif(X, y, discrete_features=True)
pd.Series(mi, index=feature_names).sort_values(ascending=False)

GenHlth                 0.074543
HighBP                  0.066592
AgeGroup                0.053803
BMI                     0.040071
HighChol                0.035569
DiffWalk                0.033722
Income                  0.023084
PhysActivity            0.021126
PhysHlth                0.020990
HeartDiseaseorAttack    0.020022
KidneyDisease           0.018814
Education               0.012136
CholCheck               0.008079
Stroke                  0.007636
COPD                    0.006554
HvyAlcoholConsump       0.004987
MentHlth                0.003539
Smoker                  0.003211
Asthma                  0.001839
Sex                     0.001123
AnyHealthcare           0.001091
NoDocbcCost             0.000013
dtype: float64